# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "trackers-models/src/db/schema.rs"

[migrations_directory]
dir = "trackers-models/migrations"
