version: "3.9"
services:
  
  # Database
  database:
    hostname: "database"
    restart: always
    image: "postgres:latest"
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    command: postgres -c shared_buffers=512MB -c wal_buffers=64MB -c work_mem=8MB
    env_file: .env
    networks:
      - app-net
      
  # Common images used to build api and web-ui
  trackers-chef:
    image: trackers-chef:${TAG:-latest}
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.chef
    env_file: .env
  trackers-planner:
    image: trackers-planner
    env_file: .env
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile.planner
    depends_on:
      trackers-chef:
        condition: service_completed_successfully
  
  # Api server
  api:
    image: api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.api
    env_file: .env
    ports:
      - "4000:4000"
    networks:
      - app-net
    depends_on:
      trackers-chef:
        condition: service_completed_successfully
      trackers-planner:
        condition: service_completed_successfully
      
  # Migrations tool
  migrator:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.models
    env_file: .env
    volumes:
      - ./trackers-models:/app
    networks:
      - app-net
    deploy:
      mode: global

networks:
  app-net:
    driver: bridge
