//! Models specific to mapping to the database representation and other symbols
//! hidden behind the _`diesel`_ feature.
//!
//! The [db](crate::db) contains the [schema](crate::db::schema) module which
//! is generated by the diesel cli tool. It also contains models which do not
//! map directly to the API responses of `tracke.rs` but instead they are used
//! to serialize data in the PostgreSQL database.

pub mod schema;
pub mod task;
pub use task::*;
pub mod user;
pub use user::*;
