[alias]
api_dev = "run --features local-dev"
ui_dev = "leptos watch --project trackers-web-ui --features local-dev"

[build]
rustflags = "--cfg uuid_unstable"

[registries.crates-io]
protocol = "sparse"