.git
db_data
target
*/target
.gitignore
*/.gitignore
Cargo.lock
*/Cargo.lock
LICENSE
*/LICENSE
*.md
docker-compose.yml
.docker
.env


trackers-api-server/src
trackers-web-ui/assets
trackers-web-ui/style
trackers-web-ui/end2end
trackers-web-ui/src