FROM rustlang/rust:nightly-slim as trackers-chef
RUN apt-get update \
    && apt-get install --no-install-recommends lld clang -y \
    && cargo install cargo-chef --locked --no-track \
    && rustup target add wasm32-unknown-unknown \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

