.git
db_data
target
*/target
.gitignore
*/.gitignore
LICENSE
*/LICENSE
*.md
diesel.toml
docker-compose.yml
.docker
.env
.env*


trackers-web-ui/assets
trackers-web-ui/end2end
trackers-web-ui/style
trackers-models/migrations