.git
db_data
target
*/target
.gitignore
*/.gitignore
LICENSE
*/LICENSE
*.md
diesel.toml
docker-compose.yml
.docker
.env


trackers-web-ui/assets
trackers-web-ui/style
trackers-web-ui/end2end
tracker-models/migrations